export enum DomainErrorCode {
  RESEARCHER_NOT_FOUND = 'RESEARCHER_NOT_FOUND',
  RESEARCHER_DNI_ALREADY_EXISTS = 'RESEARCHER_DNI_ALREADY_EXISTS',
  RESEARCHER_EMAIL_ALREADY_EXISTS = 'RESEARCHER_EMAIL_ALREADY_EXISTS',
}
