export enum DomainErrorCode {
  RESEARCHER_NOT_FOUND = 'RESEARCHER_NOT_FOUND',
  RESEARCHER_DNI_ALREADY_EXISTS = 'RESEARCHER_DNI_ALREADY_EXISTS',
  RESEARCHER_EMAIL_ALREADY_EXISTS = 'RESEARCHER_EMAIL_ALREADY_EXISTS',
  INSTITUTION_NOT_FOUND = 'INSTITUTION_NOT_FOUND',
  INSTITUTION_NAME_ALREADY_EXISTS = 'INSTITUTION_NAME_ALREADY_EXISTS',
  FACULTY_NOT_FOUND = 'FACULTY_NOT_FOUND',
  FACULTY_NAME_ALREADY_EXISTS = 'FACULTY_NAME_ALREADY_EXISTS',
}
